server:
  port: 8084

spring:
  application:
    name: payment-service

  kafka:
    bootstrap-servers: localhost:29092
    properties:
      schema.registry.url: http://localhost:8081
      specific.avro.reader: true
    consumer:
      auto-offset-reset: earliest
      group-id: payment-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
